import { TokenPayload, ConsentScope, ConsentPurpose, BPReading } from '../types';

/**
 * MyVita consent-token helpers.
 *
 * This is a JWT-style demo token for the hackathon:
 * header.payload.signature
 *
 * IMPORTANT:
 * The signature below is a deterministic demo signature, not production
 * cryptography. A production system should sign/verify tokens on the backend.
 */

type ConsentTokenInput = {
  consentId: string;
  patientName: string;
  recipient: string;
  scope: ConsentScope;
  purpose: ConsentPurpose;
  readingIds: string[];
  expiresAt: number;
  readingsData?: BPReading[];
  patientId?: string;
};

type TokenHeader = {
  alg: string;
  typ: string;
  engine: string;
};

const TOKEN_ALGORITHM = 'VH-ES256';
const TOKEN_ENGINE = 'MyVita/Consent-v1';

/**
 * Encode UTF-8 text as base64url.
 * Using TextEncoder avoids btoa() failures when the payload contains
 * names, emojis, or other non-ASCII characters.
 */
function base64UrlEncode(value: string): string {
  const bytes = new TextEncoder().encode(value);

  let binary = '';
  const chunkSize = 0x8000;

  for (let i = 0; i < bytes.length; i += chunkSize) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunkSize));
  }

  return btoa(binary)
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/g, '');
}

/**
 * Decode base64url into UTF-8 text.
 */
function base64UrlDecode(value: string): string {
  let base64 = value.replace(/-/g, '+').replace(/_/g, '/');

  while (base64.length % 4 !== 0) {
    base64 += '=';
  }

  const binary = atob(base64);
  const bytes = Uint8Array.from(binary, (char) => char.charCodeAt(0));

  return new TextDecoder().decode(bytes);
}

/**
 * Demo signature.
 *
 * Keep this formula stable so tokens generated by the current ConsentModal
 * remain compatible with the decoder.
 */
function createDemoSignature(consentId: string, expiresAt: number): string {
  return `${consentId.slice(0, 8)}_${expiresAt}_MYVITA_VERIFIED`;
}

export function generateConsentToken(data: ConsentTokenInput): string {
  const header: TokenHeader = {
    alg: TOKEN_ALGORITHM,
    typ: 'JWT',
    engine: TOKEN_ENGINE,
  };

  const payload: TokenPayload = {
    consentId: data.consentId,
    patientName: data.patientName,
    recipient: data.recipient,
    scope: data.scope,
    purpose: data.purpose,
    readingIds: data.readingIds,
    readingsData: data.readingsData,
    patientId: data.patientId,
    createdAt: Date.now(),
    expiresAt: data.expiresAt,
    ver: '1.2.0',
    routing: 'rote://myvita.health/consent-gateway',
  };

  const encodedHeader = base64UrlEncode(JSON.stringify(header));
  const encodedPayload = base64UrlEncode(JSON.stringify(payload));

  const rawSignature = createDemoSignature(
    data.consentId,
    data.expiresAt
  );

  const encodedSignature = base64UrlEncode(rawSignature);

  return `${encodedHeader}.${encodedPayload}.${encodedSignature}`;
}

/**
 * Decodes and validates the MyVita JWT-style demo token.
 *
 * validFormat is false when:
 * - the token does not contain exactly 3 parts
 * - header/payload/signature cannot be decoded
 * - required payload fields are missing
 * - the demo signature does not match the payload
 */
export function decodeConsentToken(token: string): {
  validFormat: boolean;
  payload: TokenPayload | null;
  rawHeader: TokenHeader | null;
} {
  try {
    if (!token || typeof token !== 'string') {
      return {
        validFormat: false,
        payload: null,
        rawHeader: null,
      };
    }

    const parts = token.trim().split('.');

    if (parts.length !== 3 || parts.some((part) => part.length === 0)) {
      return {
        validFormat: false,
        payload: null,
        rawHeader: null,
      };
    }

    const [encodedHeader, encodedPayload, encodedSignature] = parts;

    const header = JSON.parse(
      base64UrlDecode(encodedHeader)
    ) as TokenHeader;

    const payload = JSON.parse(
      base64UrlDecode(encodedPayload)
    ) as TokenPayload;

    const suppliedSignature = base64UrlDecode(encodedSignature);

    // Validate header structure.
    if (
      header.typ !== 'JWT' ||
      header.alg !== TOKEN_ALGORITHM ||
      header.engine !== TOKEN_ENGINE
    ) {
      return {
        validFormat: false,
        payload: null,
        rawHeader: header,
      };
    }

    // Validate the fields required by TokenPayload.
    if (
      !payload.consentId ||
      !payload.patientName ||
      !payload.recipient ||
      !payload.scope ||
      !payload.purpose ||
      !Array.isArray(payload.readingIds) ||
      typeof payload.createdAt !== 'number' ||
      typeof payload.expiresAt !== 'number' ||
      typeof payload.ver !== 'string' ||
      typeof payload.routing !== 'string'
    ) {
      return {
        validFormat: false,
        payload: null,
        rawHeader: header,
      };
    }

    // Validate the deterministic hackathon signature.
    const expectedSignature = createDemoSignature(
      payload.consentId,
      payload.expiresAt
    );

    if (suppliedSignature !== expectedSignature) {
      return {
        validFormat: false,
        payload: null,
        rawHeader: header,
      };
    }

    return {
      validFormat: true,
      payload,
      rawHeader: header,
    };
  } catch (error) {
    console.warn('MyVita consent token decode failed:', error);

    return {
      validFormat: false,
      payload: null,
      rawHeader: null,
    };
  }
}
